version: '3'

volumes:
  pydigest_postgres_data:
  pydigest_postgres_data_backups:

services:
  postgres:
    build:
      context: .
      dockerfile: ./deploy/postgres/Dockerfile
    image: project_production_postgres
    container_name: pydigest_postgres
    volumes:
      - pydigest_postgres_data:/var/lib/postgresql/data:Z
      - pydigest_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  memcached:
    container_name: pydigest_memcached
    image: memcached:latest
    ports:
        - "11211:11211"
