[tool.poetry]
name = "pythondigest"
version = "0.1.0"
description = ""
authors = ["axsapronov <a@sapronov.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = {extras = ["argon2"], version = "^4.2.3"}
django-bootstrap-form = ">=3.4"
django-digg-paginator = ">=0.2.0"
django-user-accounts = ">=3.2.0"
django-taggit-autosuggest = ">=0.4.1"
django-taggit = ">=4.0.0"
django-modeladmin-reorder = ">=0.3.1"
django-ckeditor = ">=6.7.0"
django-siteblocks = ">=1.2.1"
django-cachalot = ">=2.6.1"
django-compressor = ">=4.4"
django-secretballot = ">=2.0.0"
django-likes = {git = "https://github.com/axsapronov/django-likes.git", rev = "django4-signals"}
django-debug-toolbar = ">=4.1.0"
django-remdow = ">=0.0.7"
requests = ">=2.31.0"
lxml = ">=4.9.3"
pyyaml = ">=6.0.1"
beautifulsoup4 = ">=4.12.2"
feedparser = ">=6.0.10"
pytils = ">=0.4.1"
sorl-thumbnail = ">=12.9.0"
stem = ">=1.8.2"
urlobject = ">=2.4.3"
micawber = ">=0.5.5"
rsa = ">=4.9"
twx-botapi = "3.6.1"
google-api-python-client = ">=2.95.0"
tweepy = "<4"
funcy = ">=2.0"
pillow = ">=10.0.0"
unidecode = ">=1.3.6"
readability-lxml = {git = "https://github.com/buriy/python-readability.git", branch = "master"}
psycopg2-binary = "^2.9.6"
pymemcache = "^4.0.0"
django-browser-reload = "^1.11.0"
django-bootstrap3 = "^22.2"
django-yaturbo = "^1.0.1"
bleach = "^5.0.1"
django-environ = "<1.0"
django-redis = "^5.3.0"
sentry-sdk = "^1.28.1"
django-letsencrypt = "^4.1.0"
django-cache-memoize = "^0.1.10"
django-htmlmin = "^0.11.0"
uwsgi = "^2.0.22"
whitenoise = {extras = ["brotli"], version = "^6.5.0"}
uvicorn = "^0.26.0"
lingua-language-detector = "^1.3.2"
vk = ">=3.0"

[tool.poetry.group.test.dependencies]
django-stubs = ">=4.2.3"
pytest = ">=7.4.0"
pytest-sugar = ">=0.9.7"
pytest-django = ">=4.5.2"
factory-boy = ">=3.3.0"
mock = ">=5.1.0"

[tool.poetry.group.dev.dependencies]
flake8 = ">=6.1.0"
flake8-isort = ">=6.0.0"
coverage = ">=7.2.7"
black = ">=23.7.0"
pylint-django = ">=2.5.3"
pre-commit = ">=3.3.3"
django-extra-checks = ">=0.13.3"
django-migration-linter = ">=5.0.0"
autoflake = ">=2.2.0"
detect-secrets = ">=1.4.0"
safety = ">=2.3.5"

[tool.black]
line-length = 119
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
