[tool.poetry]
name = "pythondigest"
version = "0.1.0"
description = ""
authors = ["axsapronov <a@sapronov.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.4.10"
Django = "<3"
django-concurrency = "<2.1"
django-bootstrap-form = ">3"
django-digg-paginator = ">=0.1.3"
django-user-accounts = "<3"
django-taggit-autosuggest = ">=0.3.0"
django-taggit = "<1.0"
django-modeladmin-reorder = ">=0.3.1"
django-ckeditor = "<6.0.0"
django-siteblocks = "<1.0"
django-cachalot = "<2.2.0"
django-controlcenter = ">=0.3.1"
django-compressor = ">=2.1"
django-htmlmin = ">=0.9.1"
django-secretballot = ">=2.0.0"
django-likes = ">=2.0.1"
django-debug-toolbar = ">=1.5"
django-remdow = ">=0.0.6"
requests = ">=2.11.1"
lxml = "<4.4.0"
PyYAML = "<5.3"
beautifulsoup4 = ">=4.5.1"
feedparser = "<6"
pytils = ">=0.3"
sorl-thumbnail = ">=12.3"
stem = ">=1.4.0"
URLObject = ">=2.4.2"
readability-lxml = ">=0.6.2"
micawber = ">=0.3.3"
unidecode = "<=1.3.6"
python-social-auth = {extras = ["django"], version = "^0.3.6"}
rsa = "<=4.9"
"twx.botapi" = "<3.6.2"
google-api-python-client = ">=1.5.3"
tweepy = ">=3.5.0"
typing = ">=3.10.0.0"
funcy = ">=1.7.1"
arrow = ">=0.8.0"
pytest-runner = "<=5.2"
pytest = "<=4.6"
tox = ">=2.3.1"
mock = ">=2.0.0"
Pillow = "<6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
