[tool.poetry]
name = "pythondigest"
version = "0.1.0"
description = ""
authors = ["axsapronov <a@sapronov.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.4.10"
Django = ">=1.9,<2.0"
django-concurrency = "^1.3.1"
django-rosetta = "^0.7.12"
django-bootstrap-form = "^3.2.1"
django-digg-paginator = "^0.1.3"
django-user-accounts = "^1.3.1"
django-taggit-autosuggest = "^0.3.0"
django-taggit = "^0.21.2"
django-modeladmin-reorder = "^0.3.1"
django-ckeditor = "^5.1.0"
django-q = "^0.7.18"
django-siteblocks = "^0.5.1"
django-cachalot = "^1.2.1"
django-picklefield = "^0.3.2"
django-controlcenter = "^0.3.1"
django-compressor = "^2.1"
django-htmlmin = "^0.9.1"
django-secretballot = "^2.0.0"
django-likes = "^2.0.1"
django-debug-toolbar = "^1.5"
django-remdow = "^0.0.6"
python-memcached = "^1.58"
requests = "^2.11.1"
lxml = "^3.6.4"
PyYAML = "^3.12"
beautifulsoup4 = "^4.5.1"
feedparser = "^5.2.1"
Pillow = "^3.3.1"
pytils = "^0.3"
sorl-thumbnail = "^12.3"
stem = "^1.4.0"
URLObject = "^2.4.2"
readability-lxml = "^0.6.2"
micawber = "^0.3.3"
unidecode = "^0.4.19"
python-social-auth = {extras = ["django"], version = "^0.3.6"}
rsa = "^3.4.2"
"twx.botapi" = "^2.1.0"
google-api-python-client = "^1.5.3"
tweepy = "^3.5.0"
typing = "^3.10.0.0"
funcy = "^1.7.1"
arrow = "^0.8.0"
pytest-runner = "<=5.2"
pytest = "<=4.6"
tox = "^2.3.1"
mock = "^2.0.0"
Fabric = "^1.12.0"
django = "<1.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
