version: '3'

services:
  django:
    image: pythondigest/pythondigest:${COMMIT_TAG}
    container_name: pydigest_django
    volumes:
      - ${PWD}/static:/app/static/
      - ${PWD}/media:/app/media/
      - ${PWD}/dataset:/app/dataset/
      - ${PWD}/pages:/app/pages/
      - ${PWD}/report:/app/report/
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - BASE_DOMAIN=${BASE_DOMAIN}
      - USE_DOCKER=${USE_DOCKER}
      - GITTER_TOKEN=${GITTER_TOKEN}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_TOKEN=${TWITTER_TOKEN}
      - TWITTER_TOKEN_SECRET=${TWITTER_TOKEN_SECRET}
      - TGM_BOT_ACCESS_TOKEN=${TGM_BOT_ACCESS_TOKEN}
      - TGM_CHANNEL=${TGM_CHANNEL}
      - IFTTT_MAKER_KEY=${IFTTT_MAKER_KEY}
      - VK_APP_ID=${VK_APP_ID}
      - VK_LOGIN=${VK_LOGIN}
      - VK_PASSWORD=${VK_PASSWORD}
      - CHAD_API_KEY=${CHAD_API_KEY}
      - CHAD_API_MODEL=${CHAD_API_MODEL}
      - CLS_ENABLED=${CLS_ENABLED}
      - CLS_URL_BASE=${CLS_URL_BASE}
    ports:
      - "8000:8000"
    command: bash -c "
      echo 'Prepare and run'
      && echo 'Migrate migrations'
      && python manage.py migrate --no-input
      && python manage.py collectstatic --no-input
      && cp /app/humans.txt /app/static/
      && cp /app/robots.txt /app/static/
      && uwsgi --ini deploy/uwsgi.ini"

      # && uvicorn --host 0.0.0.0 --port 8000 --reload conf.asgi:application"

      # commands after restore old backup
      # && echo 'Fake exists migration (after restore backup)'
      # && python manage.py migrate secretballot 0001 --fake --no-input
      # && python manage.py migrate thumbnail 0001 --fake --no-input
      # && python manage.py migrate secretballot 0002 --fake --no-input
      # && python manage.py migrate --no-input
    networks:
      - py_digest

networks:
  py_digest:
    external: true
