version: '3'

services:
  django:
    image: pythondigest/pythondigest:${COMMIT_SHA}
    container_name: pydigest_django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
