version: '3'

volumes:
  pydigest_postgres_data: {}
  pydigest_postgres_data_backups: {}

services:
  django: &django
    build:
      context: ../
      dockerfile: deploy/django/Dockerfile
    image: pydigest_django
    container_name: pydigest_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - ..:/app:z
    env_file:
      - ../.envs/.local/.django
      - ../.envs/.local/.postgres
    ports:
      - "8000:8000"
    # command: echo "hi"
    # command: pip freeze
    # command: python manage.py test
    # command: poetry export -f requirements.txt -o requirements_3.6.txt
    # command: sleep 86400
    # command: pip freeze > requirements_3.4.txt
    # command: poetry install
    # command: cat poetry.lock > poetry.lock
    # command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    # command: ls

  postgres:
    build:
      context: ..
      dockerfile: ./deploy/postgres/Dockerfile
    image: pydigest_postgres
    container_name: pydigest_postgres
    volumes:
      - pydigest_postgres_data:/var/lib/postgresql/data:Z
      - pydigest_postgres_data_backups:/backups:z
    env_file:
      - ../.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: pydigest_redis
