version: '3'

services:
  django:
    image: pythondigest/pythondigest:renew
    container_name: pydigest_django
    volumes:
      - ${PWD}/static:/app/static/
      - ${PWD}/media:/app/media/
    ports:
      - "8000:8000"
    command: bash -c "
      python manage.py collectstatic --no-input
      && cp /app/humans.txt /app/static/
      && cp /app/robots.txt /app/static/
      && python manage.py runserver 0.0.0.0:8000
      "
