version: '3'

services:
  django:
    image: pythondigest/pythondigest:renew
    container_name: pydigest_django
    volumes:
      - ${PWD}/static:/app/static/
      - ${PWD}/media:/app/media/
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    command: bash -c "
      manage.py migrate secretballot 0001 --fake --no-input
      && python manage.py migrate --no-input
      && python manage.py collectstatic --no-input
      && cp /app/humans.txt /app/static/
      && cp /app/robots.txt /app/static/
      && python manage.py runserver 0.0.0.0:8000"
