version: '3'

volumes:
  pydigest_postgres_data: {}
  pydigest_postgres_data_backups: {}

services:
  django: &django
    build:
      context: ../
      dockerfile: deploy/django/Dockerfile
    image: pydigest_django
    container_name: pydigest_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - ..:/app:z
    env_file:
      - ../.envs/.local/.django
      - ../.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: python manage.py runserver
    # command: uwsgi --ini deploy/uwsgi.ini

  postgres:
    build:
      context: ..
      dockerfile: ./deploy/postgres/Dockerfile
    image: pydigest_postgres
    container_name: pydigest_postgres
    volumes:
      - pydigest_postgres_data:/var/lib/postgresql/data:Z
      - pydigest_postgres_data_backups:/backups:z
    env_file:
      - ../.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: pydigest_redis
